services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # porta de comunicação AMQP
      - "15672:15672"   # interface de administração
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - video-net

  auth-service:
    build: ./services/auth-service
    image: raildosantos/auth-service:latest
    ports:
      - "3001:3001"
    networks:
      - video-net
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
      DATABASE_URL: ${DATABASE_URL}

  upload-service:
    build: ./services/upload-service
    image: raildosantos/upload-service:latest
    volumes:
      - ./services/upload-service/uploads:/app/uploads
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
    networks:
      - video-net
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672

  processing-service:
    build: ./services/processing-service
    image: raildosantos/processing-service:latest
    volumes:
      - ./services/processing-service/frames:/app/frames
      - ./services/upload-service/uploads:/app/uploads
    depends_on:
      - rabbitmq
    networks:
      - video-net
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672

  zipping-service:
    build: ./services/zipping-service
    image: raildosantos/zipping-service:latest
    volumes:
      - ./services/processing-service/frames:/app/frames
      - ./services/zipping-service/zips:/app/zips
    depends_on:
      - rabbitmq
    networks:
      - video-net
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672

  notification-service:
    build: ./services/notification-service
    image:  raildosantos/notification-service:latest
    depends_on:
      - rabbitmq
    networks:
      - video-net
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}

  gateway-service:
    build: ./services/gateway-service
    image: raildosantos/gateway-service:latest
    volumes:
      - ./services/zipping-service/zips:/app/zips
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - upload-service
    networks:
      - video-net
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672

networks:
  video-net:
    driver: bridge
